[package]
name = "ramemu"
version = "0.1.9"
edition = "2021"
license = "GPL3"

[dependencies]
rustc-hash = "1.1.0"

[profile.release]
lto = true
codegen-units = 1
strip = true
opt-level = 3

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.84"
