[package]
name = "ram"
version = "0.1.3"
edition = "2021"
license = "GPL3"

[dependencies]
wasm-bindgen = { version = "0.2.84", optional = true }

[features]
wasm = ["wasm-bindgen"]

[profile.release]
lto = true
codegen-units = 1
strip = true
opt-level = 3
